-- Products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders table
create table orders (
  id bigint generated by default as identity primary key,
  user_name text not null,
  user_email text,
  order_items jsonb not null,
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Initial product data
insert into products (name) values 
  ('Weißwürste'),
  ('Wiener'),
  ('Debrecziner'),
  ('Brezen');
